inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "config//**/*"
    - "public/**/*"
    - "storage/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "config.ru"
    - "Rakefile"
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
