version: "3.8"
services:
  app:
    container_name: jot-blox-app
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace
      - jot-blox-node-modules:/workspace/frontend/node_modules

    command: sleep infinity

  db:
    container_name: jot-blox-db
    image: postgres:latest
    volumes:
      - jot-blox-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  jot-blox-node-modules:
  jot-blox-postgres-data:
